_target_: src.models.LanguageAndVisionConcat

embedding_dim: 100
model_type: concat
language_feature_dim: 256
backbone_output_dim: 1000
vision_feature_dim: 256
fusion_output_size: 256
dropout_p: 0.1
lr: 0.00001
