_target_: src.models.LanguageAndVisionConcat

embedding_dim: 768
backbone_output_dim: 1000
language_feature_dim: 256
vision_feature_dim: 256
fusion_output_size: 256
model_type: concat_bert
dropout_p: 0.1
